# This is a basic workflow to help you get started with Actions

name: Checkmarx Scan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      - name: Run Checkmarx Scan
      - env:
          CHECKMARX_SERVER: <https://ind.ast.checkmarx.net/login-organization>
          CHECKMARX_USERNAME: <kshitij.shinde@rahinfotech.com>
          CHECKMARX_PASSWORD: <Wsspdude12345!>
        run: |
          # Install Checkmarx CLI or use Checkmarx provided action if available
          # Run the Checkmarx scan command, passing necessary parameters
